# Generated by Django 4.2.20 on 2025-05-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('input_file', models.CharField(max_length=255)),
                ('output_file', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
            ],
        ),
    ]
